blogging/urls.py
from django.urls import path, include
from blogging.views import BlogListView, BlogDetailView, PostViewSet, UserViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"posts", PostViewSet)


urlpatterns = [
    path("", BlogListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    # api
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path("", include("blogging.urls")),
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

polling/urls.py
from django.urls import path, include
from .views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        # return f"{self.title} created at {self.created_date} - created by {self.author}"
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

polling/models.py
from django.db import models


# Create your models here.


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from rest_framework import viewsets, permissions
from blogging.serializers import PostSerializers, UserSerializer
from blogging.models import Post


# Create your views here.


def stub_view(request, *args, **kwargs):
    body = "Stub View\n\n"
    if args:
        body += "Args:\n"
        body += "\n".join(["\t%s" % a for a in args])
    if kwargs:
        body += "Kwargs:\n"
        body += "\n".join(["\t%s: %s" % i for i in kwargs.items()])
    return HttpResponse(body, content_type="text/plain")


class BlogListView(ListView):
    template_name = "blogging/list.html"
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )


class BlogDetailView(DetailView):
    model = Post
    template_name = "blogging/detail.html"
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = User.objects.all().order_by("-date_joined")
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited posts.
    """

    queryset = Post.objects.all().order_by("-published_date")
    serializer_class = PostSerializers
    permission_classes = [permissions.IsAuthenticated]

polling/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from polling.models import Poll


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()
        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()
        context = {"poll": poll}
        return render(request, "polling/detail.html", context)

blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
    <a class="backlink" href="/">Home</a>
    <h1>{{ post }}</h1>
    <p class="byline">
        Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
        {{ post.text }}
    </div>
    <ul class="categories">
        {% for category in post.categories.all %}
            <li>{{ category }}</li>
        {% endfor %}
    </ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}

{% block content %}
    <h1>Coolest Posts</h1>
    {% for post in post_list %}
        <div class="post">
            <h2 href="{% url 'blog_detail' post.pk %}">{{ post }}</h2>
            <p class="byline">
                Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
            </p>
            <div class="post-body">
                {{ post.text }}
            </div>
            <ul class="categories">
                {% for category in post.categories.all %}
                    <li>{{ category }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ poll.title }}</h1>
<div class="poll-body">
    {{ poll.text }}
</div>
<div class="poll-score">
    Current score: {{ poll.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
    <h1>Polls</h1>
    {% for poll in poll_list %}
        <div class="poll">
            <h2>
                <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
            </h2>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Django Blog</title>
</head>
<body>


<div id="header">
    <ul id="control-bar">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
            <li><a href="{% url 'logout' %}">logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}">login</a></li>
        {% endif %}
    </ul>
</div>

<div id="container">
    <div id="content">
        {% block content %}
            [content will go here]
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>My Blog Login</h1>
    <form action="" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Log In"></p>
    </form>
{% endblock %}